name: Custom CICD pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove old node_modules
        run: rm -rf node_modules

      - name: Install dependencies
        run: npm ci

      - name: Stop old application
        run: pkill -f "node" || true

      - name: Start application
        run: nohup npm run dev > app.log 2>&1 &