name: Deploy Node App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          docker exec mycontainer sh -c "cd /coding/cicd && git pull"

      - name: Install dependencies
        run: |
          docker exec mycontainer sh -c "cd /coding/cicd && npm install"

      - name: Restart app
        run: |
          docker exec mycontainer sh -c "pkill node || true"

          docker exec -d mycontainer sh -c "
            cd /coding/cicd &&
            nohup npm run dev > app.log 2>&1 &
          "